# Generated by Django 4.2 on 2023-09-26 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("written_app", "0002_alter_topic_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("student", models.CharField(max_length=100)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="written_app.topic",
                    ),
                ),
            ],
        ),
    ]
