# Generated by Django 4.2 on 2023-09-26 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("written_app", "0003_topicdetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topicdetail",
            old_name="topic",
            new_name="title",
        ),
    ]
