# Generated by Django 4.2 on 2023-09-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("written_app", "0004_rename_topic_topicdetail_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicdetail",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="written_app.topic"
            ),
        ),
    ]
