# Generated by Django 4.2 on 2023-09-28 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("written_app", "0006_alter_topic_id_alter_topicdetail_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="slug",
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="topic",
            name="id",
            field=models.URLField(
                default=uuid.UUID("4e7b9566-60e6-5336-9360-069a3c16a6c4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="topicdetail",
            name="id",
            field=models.URLField(
                default=uuid.UUID("3e5c2108-09da-50fd-800b-e1c7edd4a9c7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
