# Generated by Django 4.2 on 2023-10-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("written_app", "0011_alter_topic_id_alter_topicdetail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(editable=False),
        ),
    ]
